### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by crshrprt** [simohnf/sjf_verb#1]
Thank you for this interesting plugin.

I can't find if the source is released under a license. Is there a license?

**Comment by crshrprt** [comment]
I saw you added a license, thank you very much.

**Comment by simohnf** [comment]
Hi, thanks for pointing this issue out - I had added a license to my main DSP repo, but you are correct I should have added it to each of the plugins as well.

I am in the process of (slowly) improving all of these, but I hope you still enjoy them
